routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\QuestionsComplaintController;
use App\Http\Controllers\CategoryDriverLicenseController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TopicRoadMarkingController;
use App\Http\Controllers\TopicRoadSignController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\Auth\RegisterController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::domain(env('APP_DOMAIN_NAME'))->group(function () {
    Route::get('/', function () {
        return view('errors.soon');
    });
});

Route::domain('teacher.' . env('APP_DOMAIN_NAME'))->group(function () {
    Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('/register', [RegisterController::class, 'register'])->name('register');
});

Route::get('/', function () {
    return redirect()->route('login');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('index', [\App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');

    Route::middleware('can:languages')->group(function () {
        Route::resource('languages', LanguageController::class)->except(['show']);
        Route::post('languages/sort', [LanguageController::class, 'sort'])->name('languages.sort');
    });

    Route::resource('logs', \App\Http\Controllers\LogController::class)->only(['index'])->middleware('can:logs');

    Route::resource('instructions', \App\Http\Controllers\InstructionController::class)->except('show');
    Route::post('instructions/sort', [\App\Http\Controllers\InstructionController::class, 'sort'])->name('instructions.sort');

    Route::middleware(['can:teachers'])->group(function () {
        Route::resource('teachers', TeacherController::class)->except(['show']);
        Route::post('teachers/get-autocomplete-teacher', [TeacherController::class, 'getAutocompleteTeacher'])
            ->name('teachers.getAutocompleteTeacher');
        Route::post('teachers/get-autocomplete-email', [TeacherController::class, 'getAutocompleteEmail'])
            ->name('teachers.getAutocompleteEmail');
        Route::post('teachers/get-autocomplete-promo-code', [TeacherController::class, 'getAutocompletePromoCode'])
            ->name('teachers.getAutocompletePromoCode');
    });

    Route::middleware(['can:display-students'])->group(function () {
        Route::resource('students', StudentController::class)->except(['show']);
        Route::post('students/get-autocomplete-teacher', [StudentController::class, 'getAutocompleteTeacher'])
            ->name('students.getAutocompleteTeacher');
        Route::post('students/get-autocomplete-student', [StudentController::class, 'getAutocompleteStudent'])
            ->name('students.getAutocompleteStudent');
        Route::post('students/get-autocomplete-group', [StudentController::class, 'getAutocompleteGroup'])
            ->name('students.getAutocompleteGroup');
        Route::post('students/get-autocomplete-email', [StudentController::class, 'getAutocompleteEmail'])
            ->name('students.getAutocompleteEmail');
        Route::post('students/get-autocomplete-promo-code', [StudentController::class, 'getAutocompletePromoCode'])
            ->name('students.getAutocompletePromoCode');
    });

    Route::get('students/export', [StudentController::class, 'export'])->name('students.export')
        ->middleware('can:teachers');
    Route::post('students/action-multiple', [StudentController::class, 'actionMultiple'])
        ->name('students.actionMultiple')
        ->middleware('can:student-actions');

    Route::middleware(['can:groups'])->group(function () {
        Route::resource('groups', GroupController::class)->except(['show']);
        Route::post('groups/get-autocomplete-teacher', [GroupController::class, 'getAutocompleteTeacher'])->name('groups.getAutocompleteTeacher');
        Route::post('groups/get-autocomplete-group', [GroupController::class, 'getAutocompleteGroup'])->name('groups.getAutocompleteGroup');
    });

    Route::resource('category-driver-licenses', CategoryDriverLicenseController::class)
        ->only(['index', 'store'])->middleware('can:category-driver-licenses');

    Route::name('handbook.')->middleware('can:handbook')->prefix('handbook')->group(function () {
        Route::resource('theme-traffic-rules', \App\Http\Controllers\TopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['theme-traffic-rules' => 'topic_traffic_rule']);
    });

    Route::name('theory.')->middleware('can:theory')->prefix('theories')->group(function () {
        Route::resource('internal-theme-traffic-rules', \App\Http\Controllers\InternalTopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['internal-theme-traffic-rules' => 'internal_topic_traffic_rule']);

        Route::resource('item-traffic-rules', \App\Http\Controllers\ItemTrafficRuleController::class)->except(['show']);
        Route::post('item-traffic-rules/get-autocomplete-item', [\App\Http\Controllers\ItemTrafficRuleController::class, 'getAutocompleteItem'])->name('item-traffic-rules.getAutocompleteItem');
        Route::post('item-traffic-rules/sort', [\App\Http\Controllers\ItemTrafficRuleController::class, 'sort'])->name('item-traffic-rules.sort');

        Route::resource('road-markings', TopicRoadMarkingController::class)->except(['show'])->parameters(['road-markings' => 'topic_road_marking']);
        Route::get('road-markings/description', [TopicRoadMarkingController::class, 'editDescription'])->name('road-markings.editDescription');
        Route::post('road-markings/description', [TopicRoadMarkingController::class, 'updateDescription'])->name('road-markings.updateDescription');

        Route::resource('road-signs', TopicRoadSignController::class)->except(['show'])->parameters(['road-signs' => 'topic_road_sign']);
        Route::get('road-signs/description', [TopicRoadSignController::class, 'editDescription'])->name('road-signs.editDescription');
        Route::post('road-signs/description', [TopicRoadSignController::class, 'updateDescription'])->name('road-signs.updateDescription');

        Route::resource('markings', \App\Http\Controllers\MarkingController::class)->except(['show']);
        Route::post('markings/get-autocomplete-markings', [\App\Http\Controllers\MarkingController::class, 'getAutocompleteMarking'])->name('markings.getAutocompleteMarking');
        Route::post('markings/sort', [\App\Http\Controllers\MarkingController::class, 'sort'])->name('markings.sort');

        Route::resource('signs', \App\Http\Controllers\SignController::class)->except(['show']);
        Route::post('signs/get-autocomplete-signs', [\App\Http\Controllers\SignController::class, 'getAutocompleteSign'])->name('signs.getAutocompleteSign');
        Route::post('signs/sort', [\App\Http\Controllers\SignController::class, 'sort'])->name('signs.sort');

        Route::get('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'index'])->name('regulator.index');
        Route::post('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'update'])->name('regulator.update');

        Route::get('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'index'])->name('traffic-light.index');
        Route::post('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'update'])->name('traffic-light.update');

        Route::get('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'index'])->name('video-lessons-traffic-rule.index');
        Route::post('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'update'])->name('video-lessons-traffic-rule.update');
    });

    Route::name('issue-management.')->middleware('can:issue-management')->prefix('issue-management')->group(function () {
        Route::resource('questions', QuestionController::class)->except(['show']);
        Route::get('questions/{question}/duplicate', [QuestionController::class, 'duplicate'])->name('questions.duplicate');
        Route::post('questions/{duplicateQuestion}/store-duplicate', [QuestionController::class, 'storeDuplicate'])->name('questions.store-duplicate');

        Route::resource('questions-complaints', QuestionsComplaintController::class)->only(['index', 'destroy']);

        Route::get('frequent-mistakes', [QuestionController::class, 'frequentMistakes'])->name('frequent-mistakes.index');
        Route::post('frequent-mistakes/reset', [QuestionController::class, 'resetFrequentMistakes'])->name('frequent-mistakes.reset');
    });

    Route::middleware('can:support-services')->group(function () {
        Route::resource('support-services', \App\Http\Controllers\SocialSupportServiceController::class)
            ->except(['show'])
            ->parameters(['support-services' => 'social_support_service']);
    });

    Route::resource('translation-categories', \App\Http\Controllers\TranslationCategoryController::class)
        ->except(['show'])->middleware('can:translations');
    Route::resource('translations', \App\Http\Controllers\TranslationController::class)

resources/views/handbook/road-signs/create.blade.php
@extends('layouts.master')

@section('title') Додавання нової категорії @endsection

@section('css')
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <link rel="stylesheet" href="{{ URL::asset('/assets/css/emojipicker.css') }}">
@endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Додавання нової категорії</h4>
                {{ Breadcrumbs::render('type_road_signs.create') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach($languages as $language)
                            <li class="nav-item">
                                <a class="nav-link {{ $language->is_default ? 'active' : '' }}" data-toggle="tab"
                                   href="#{{ $language->abbreviation }}" role="tab">
                                    <span class="d-block d-sm-none"><img src="{{ \Storage::url($language->flag) }}"
                                                                         style="max-width:64px;max-height:24px;"></span>
                                    <span class="d-none d-sm-block">{{ $language->title }}</span>
                                </a>
                            </li>
                        @endforeach
                    </ul>

                    <form method="POST" action="{{ route('theory.road-signs.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="tab-content">
                            @foreach($languages as $language)
                                <div class="tab-pane p-3 {{ $language->is_default ? 'active' : '' }}" id="{{ $language->abbreviation }}" role="tabpanel">
                                    @if($language->is_default)
                                        <div class="form-group row">
                                            <label for="number" class="col-sm-2 col-form-label">Категорія № *</label>
                                            <div class="col-sm-2">
                                                <input class="form-control @error('number')is-invalid @enderror" type="text"
                                                       name="number" value="{{ old('number') }}" id="number">
                                                @error('number')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="image" class="col-sm-2 col-form-label">Зображення (200x200 px) *</label>
                                            <div class="col-sm-2">
                                                <input type="file" name="image" id="image">
                                                @error('image')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                            </div>
                                        </div>
                                    @endif

                                    <div class="form-group row">
                                        <label for="name_{{ $language->id }}"
                                               class="col-sm-2 col-form-label">Назва {{ $language->is_default ? '*' : '' }}</label>
                                        <div class="col-sm-5">
                                            <input type="text"
                                                   class="form-control @error('translate.name.' . $language->id)is-invalid @enderror"
                                                   id="name_{{ $language->id }}"
                                                   name="translate[name][{{ $language->id }}]"
                                                   value="{{ old('translate.name.'. $language->id) }}">

                                            @error('translate.name.' . $language->id)
                                            <div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="description_{{ $language->id }}" class="col-sm-2 col-form-label">Опис</label>
                                        <div class="col-sm-5">
                                            <textarea
                                                class="form-control @error('translate.description.' . $language->id)is-invalid @enderror"
                                                id="description_{{ $language->id }}"
                                                data-action="markdown"
                                                name="translate[description][{{ $language->id }}]">{{ old('translate.description.'. $language->id) }}</textarea>
                                            @error('translate.description.' . $language->id)
                                            <div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                        </div>

                                        @include('inc.token-description')
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('theory.road-signs.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

@section('script')
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
    <script src="{{ URL::asset('/assets/js/inputEmoji.js') }}"></script>
    <script src="{{ URL::asset('/assets/js/emojis.js') }}"></script>

    <script>
        $(function () {
            document.oninput = function() {
                let input = document.getElementById('number');
                input.value = input.value.replace (/[^\d]/g, '');
            }

            $('textarea[data-action="markdown"]').each(function() {
                new EasyMDE({
                    element: this,
                    toolbar: ["bold", "|", "link", "|", {
                        name: "smile",
                        action: (editor) => {
                            $(this).emojiList(editor);
                        },
                        className: "fa fa-smile",
                        title: "Smile",
                    }, "|", "preview"],
                    status: false,
                    spellChecker: false,
                    renderingConfig: {
                        singleLineBreaks: false
                    }
                });
            });
        });
    </script>
@endsection

resources/views/handbook/road-signs/description.blade.php
@extends('layouts.master')

@section('title') Загальний опис до категорій @endsection

@section('css')
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <link rel="stylesheet" href="{{ URL::asset('/assets/css/emojipicker.css') }}">
@endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Загальний опис до категорій</h4>
                {{ Breadcrumbs::render('type_road_signs.description') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach($languages as $language)
                            <li class="nav-item">
                                <a class="nav-link {{ $language->is_default ? 'active' : '' }}" data-toggle="tab"
                                   href="#{{ $language->abbreviation }}" role="tab">
                                    <span class="d-block d-sm-none"><img src="{{ \Storage::url($language->flag) }}"
                                                                         style="max-width:64px;max-height:24px;"></span>
                                    <span class="d-none d-sm-block">{{ $language->title }}</span>
                                </a>
                            </li>
                        @endforeach
                    </ul>

                    <form method="POST" action="{{ route('theory.road-signs.updateDescription') }}">
                        @csrf

                        <div class="tab-content">
                            @foreach($languages as $language)
                                <div class="tab-pane p-3 {{ $language->is_default ? 'active' : '' }}" id="{{ $language->abbreviation }}" role="tabpanel">
                                    <div class="form-group row short-markdown">
                                        <label for="description_{{ $language->id }}" class="col-sm-2 col-form-label">Вміст</label>
                                        <div class="col-sm-5">
                                            <textarea class="form-control @error('translate.description.' . $language->id)is-invalid @enderror"
                                                id="description_{{ $language->id }}" data-action="markdown"
                                                name="translate[description][{{ $language->id }}]">{{ old('translate.description.'. $language->id, $data[$language->id]['description'] ?? '') }}</textarea>
                                            @error('translate.description.' . $language->id)
                                            <div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                        </div>

                                        <div class="col-sm-5 token-description">
                                            <p><b>ВАЖЛИВО:</b> для наповнення контентом необхідно керуватися стандартом MarkDown розмітки описаній тут: <a href="https://www.markdownguide.org/basic-syntax" target="_blank">https://www.markdownguide.org/basic-syntax</a></p>
                                            <p>Важливо пам'ятати, що згідно дизайну у мобільному пристрої із усіх стилістичних оформлень тексту, обробляється тільки жирний текст, всі інші стилі ігноруються. В веб-версії будуть відображатись всі стилі.</p>
                                            <p>Так же, в доповнення до описаного стандарту використовуються розширені теги розмітки для вставляння посилань на пункти ПДР, знаки, розмітку.</p>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('theory.road-signs.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

@section('script')
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
    <script src="{{ URL::asset('/assets/js/inputEmoji.js') }}"></script>
    <script src="{{ URL::asset('/assets/js/emojis.js') }}"></script>

    <script>
        $(function () {
            $(".select2").select2({
                minimumResultsForSearch: Infinity
            });

            $('textarea[data-action="markdown"]').each(function() {
                new EasyMDE({
                    element: this,
                    toolbar: ["bold", "|", "link", "|", {
                        name: "smile",
                        action: (editor) => {
                            $(this).emojiList(editor);
                        },
                        className: "fa fa-smile",
                        title: "Smile",
                    }, "|", "preview"],
                    status: false,
                    spellChecker: false,
                    renderingConfig: {
                        singleLineBreaks: false
                    }
                });
            });
        });
    </script>
@endsection

resources/views/handbook/road-signs/index.blade.php
@extends('layouts.master')

@section('title') @lang('translation.type_road_signs') @endsection

@section('content')

    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">@lang('translation.type_road_signs')</h4>
                {{ Breadcrumbs::render('type_road_signs') }}
            </div>
        </div>

    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center mb-3">
                        <div class="col-sm-12">
                            <div class="float-right d-md-block ">
                                <a href="{{ route('theory.road-signs.editDescription') }}"
                                   class="btn btn-primary waves-effect waves-light">Загальний опис</a>
                                <a href="{{ route('theory.road-signs.create') }}"
                                   class="btn btn-primary waves-effect waves-light">Додати категорію</a>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Категорія №</th>
                                <th>Зображення</th>
                                <th>{{ $defaultLanguage->title }}</th>
                                <th>Переклади</th>
                                <th>Опції</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($topicRoadSigns as $topicRoadSign)
                                <tr data-itemId="{{ $topicRoadSign->id }}">
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $topicRoadSign->number }}</td>
                                    <td>@empty(!$topicRoadSign->image)<img src="{{ \Storage::url($topicRoadSign->image) }}" style="max-width:64px;max-height:24px;">@endempty</td>
                                    <td>{{ $topicRoadSign->getTranslate($defaultLanguage->id)->name }}</td>
                                    <td>
                                        @foreach($languages as $language)
                                            @if(!$language->is_default)
                                                @if(empty($topicRoadSign->getTranslate($language->id)->name))
                                                    <img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:16px;opacity: 0.2;">
                                                @else
                                                    <img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:16px;">
                                                @endif
                                            @endif
                                        @endforeach
                                    </td>
                                    <td style="width: 150px;">
                                        <div class="btn-group">
                                            <a href="{{ route('theory.road-signs.edit', $topicRoadSign) }}" class="btn btn-primary">
                                                <i class="mdi mdi-pencil"></i>
                                            </a>
                                            <a href="{{ route('theory.road-signs.destroy', $topicRoadSign) }}" class="btn btn-danger"
                                               data-message="Ви дійсно хочете видалити категорію?" data-action="delete">
                                                <i class="mdi mdi-delete"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page-content -->

@endsection