routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\QuestionsComplaintController;
use App\Http\Controllers\CategoryDriverLicenseController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TopicRoadMarkingController;
use App\Http\Controllers\TopicRoadSignController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\Auth\RegisterController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::domain(env('APP_DOMAIN_NAME'))->group(function () {
    Route::get('/', function () {
        return view('errors.soon');
    });
});

Route::domain('teacher.' . env('APP_DOMAIN_NAME'))->group(function () {
    Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('/register', [RegisterController::class, 'register'])->name('register');
});

Route::get('/', function () {
    return redirect()->route('login');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('index', [\App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');

    Route::middleware('can:languages')->group(function () {
        Route::resource('languages', LanguageController::class)->except(['show']);
        Route::post('languages/sort', [LanguageController::class, 'sort'])->name('languages.sort');
    });

    Route::resource('logs', \App\Http\Controllers\LogController::class)->only(['index'])->middleware('can:logs');

    Route::resource('instructions', \App\Http\Controllers\InstructionController::class)->except('show');
    Route::post('instructions/sort', [\App\Http\Controllers\InstructionController::class, 'sort'])->name('instructions.sort');

    Route::middleware(['can:teachers'])->group(function () {
        Route::resource('teachers', TeacherController::class)->except(['show']);
        Route::post('teachers/get-autocomplete-teacher', [TeacherController::class, 'getAutocompleteTeacher'])
            ->name('teachers.getAutocompleteTeacher');
        Route::post('teachers/get-autocomplete-email', [TeacherController::class, 'getAutocompleteEmail'])
            ->name('teachers.getAutocompleteEmail');
        Route::post('teachers/get-autocomplete-promo-code', [TeacherController::class, 'getAutocompletePromoCode'])
            ->name('teachers.getAutocompletePromoCode');
    });

    Route::middleware(['can:display-students'])->group(function () {
        Route::resource('students', StudentController::class)->except(['show']);
        Route::post('students/get-autocomplete-teacher', [StudentController::class, 'getAutocompleteTeacher'])
            ->name('students.getAutocompleteTeacher');
        Route::post('students/get-autocomplete-student', [StudentController::class, 'getAutocompleteStudent'])
            ->name('students.getAutocompleteStudent');
        Route::post('students/get-autocomplete-group', [StudentController::class, 'getAutocompleteGroup'])
            ->name('students.getAutocompleteGroup');
        Route::post('students/get-autocomplete-email', [StudentController::class, 'getAutocompleteEmail'])
            ->name('students.getAutocompleteEmail');
        Route::post('students/get-autocomplete-promo-code', [StudentController::class, 'getAutocompletePromoCode'])
            ->name('students.getAutocompletePromoCode');
    });

    Route::get('students/export', [StudentController::class, 'export'])->name('students.export')
        ->middleware('can:teachers');
    Route::post('students/action-multiple', [StudentController::class, 'actionMultiple'])
        ->name('students.actionMultiple')
        ->middleware('can:student-actions');

    Route::middleware(['can:groups'])->group(function () {
        Route::resource('groups', GroupController::class)->except(['show']);
        Route::post('groups/get-autocomplete-teacher', [GroupController::class, 'getAutocompleteTeacher'])->name('groups.getAutocompleteTeacher');
        Route::post('groups/get-autocomplete-group', [GroupController::class, 'getAutocompleteGroup'])->name('groups.getAutocompleteGroup');
    });

    Route::resource('category-driver-licenses', CategoryDriverLicenseController::class)
        ->only(['index', 'store'])->middleware('can:category-driver-licenses');

    Route::name('handbook.')->middleware('can:handbook')->prefix('handbook')->group(function () {
        Route::resource('theme-traffic-rules', \App\Http\Controllers\TopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['theme-traffic-rules' => 'topic_traffic_rule']);
    });

    Route::name('theory.')->middleware('can:theory')->prefix('theories')->group(function () {
        Route::resource('internal-theme-traffic-rules', \App\Http\Controllers\InternalTopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['internal-theme-traffic-rules' => 'internal_topic_traffic_rule']);

        Route::resource('item-traffic-rules', \App\Http\Controllers\ItemTrafficRuleController::class)->except(['show']);
        Route::post('item-traffic-rules/get-autocomplete-item', [\App\Http\Controllers\ItemTrafficRuleController::class, 'getAutocompleteItem'])->name('item-traffic-rules.getAutocompleteItem');
        Route::post('item-traffic-rules/sort', [\App\Http\Controllers\ItemTrafficRuleController::class, 'sort'])->name('item-traffic-rules.sort');

        Route::resource('road-markings', TopicRoadMarkingController::class)->except(['show'])->parameters(['road-markings' => 'topic_road_marking']);
        Route::get('road-markings/description', [TopicRoadMarkingController::class, 'editDescription'])->name('road-markings.editDescription');
        Route::post('road-markings/description', [TopicRoadMarkingController::class, 'updateDescription'])->name('road-markings.updateDescription');

        Route::resource('road-signs', TopicRoadSignController::class)->except(['show'])->parameters(['road-signs' => 'topic_road_sign']);
        Route::get('road-signs/description', [TopicRoadSignController::class, 'editDescription'])->name('road-signs.editDescription');
        Route::post('road-signs/description', [TopicRoadSignController::class, 'updateDescription'])->name('road-signs.updateDescription');

        Route::resource('markings', \App\Http\Controllers\MarkingController::class)->except(['show']);
        Route::post('markings/get-autocomplete-markings', [\App\Http\Controllers\MarkingController::class, 'getAutocompleteMarking'])->name('markings.getAutocompleteMarking');
        Route::post('markings/sort', [\App\Http\Controllers\MarkingController::class, 'sort'])->name('markings.sort');

        Route::resource('signs', \App\Http\Controllers\SignController::class)->except(['show']);
        Route::post('signs/get-autocomplete-signs', [\App\Http\Controllers\SignController::class, 'getAutocompleteSign'])->name('signs.getAutocompleteSign');
        Route::post('signs/sort', [\App\Http\Controllers\SignController::class, 'sort'])->name('signs.sort');

        Route::get('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'index'])->name('regulator.index');
        Route::post('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'update'])->name('regulator.update');

        Route::get('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'index'])->name('traffic-light.index');
        Route::post('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'update'])->name('traffic-light.update');

        Route::get('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'index'])->name('video-lessons-traffic-rule.index');
        Route::post('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'update'])->name('video-lessons-traffic-rule.update');
    });

    Route::name('issue-management.')->middleware('can:issue-management')->prefix('issue-management')->group(function () {
        Route::resource('questions', QuestionController::class)->except(['show']);
        Route::get('questions/{question}/duplicate', [QuestionController::class, 'duplicate'])->name('questions.duplicate');
        Route::post('questions/{duplicateQuestion}/store-duplicate', [QuestionController::class, 'storeDuplicate'])->name('questions.store-duplicate');

        Route::resource('questions-complaints', QuestionsComplaintController::class)->only(['index', 'destroy']);

        Route::get('frequent-mistakes', [QuestionController::class, 'frequentMistakes'])->name('frequent-mistakes.index');
        Route::post('frequent-mistakes/reset', [QuestionController::class, 'resetFrequentMistakes'])->name('frequent-mistakes.reset');
    });

    Route::middleware('can:support-services')->group(function () {
        Route::resource('support-services', \App\Http\Controllers\SocialSupportServiceController::class)
            ->except(['show'])
            ->parameters(['support-services' => 'social_support_service']);
    });

    Route::resource('translation-categories', \App\Http\Controllers\TranslationCategoryController::class)
        ->except(['show'])->middleware('can:translations');
    Route::resource('translations', \App\Http\Controllers\TranslationController::class)

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use \Rutorika\Sortable\SortableTrait;

;

class Language extends Model
{
    use HasFactory, SoftDeletes, SortableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'abbreviation', 'flag', 'is_default', 'order'];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'is_default' => 'boolean',
    ];

    protected static $sortableField = 'order';

    /**
     * Scope a query get default language.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeDefault($query)
    {
        return $query->where('is_default', true);
    }

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('sorted', function (Builder $builder) {
            $builder->orderBy(self::$sortableField);
        });

        static::creating(function () {
            Cache::forget('languages');
        });

        static::updating(function () {
            Cache::forget('languages');
        });

        static::deleting(function ($language) {
            if ($language->is_default) {
                abort(403);
            }

            Cache::forget('languages');
            Storage::delete($language->flag);
            $language->next()->decrement(self::$sortableField);
        });
    }
}

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Languages\StoreRequest;
use App\Http\Requests\Languages\UpdateRequest;
use App\Models\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class LanguageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return mixed
     */
    public function index()
    {
        $languages = Language::paginate(25);

        return view('languages.index', compact('languages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return mixed
     */
    public function create()
    {
        return view('languages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Languages\StoreRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreRequest $request)
    {
        $language = Language::create($request->only([
            'title', 'abbreviation'
        ]));

        if ($request->hasFile('flag')) {
            $language->flag = $request->flag->storePublicly('public/languages/flags');
            $language->save();
        }

        return $request->action == 'save_and_stay' ?
            redirect()->route('languages.edit', $language)->with('success', 'Мову успішно створено!') :
            redirect()->route('languages.index')->with('success', 'Мову успішно створено!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Language  $language
     * @return mixed
     */
    public function edit(Language $language)
    {
        return view('languages.edit', compact('language'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Languages\UpdateRequest  $request
     * @param  \App\Models\Language  $language
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, Language $language)
    {
        $language->update($request->only([
            'title', 'abbreviation'
        ]));

        if ($request->hasFile('flag')) {
            Storage::delete($language->flag);
            $language->flag = $request->flag->storePublicly('public/languages/flags');
            $language->save();
        }

        return $request->action == 'save_and_stay' ?
            redirect()->route('languages.edit', $language)->with('success', 'Мову успішно оновлено!') :
            redirect()->route('languages.index')->with('success', 'Мову успішно оновлено!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Language  $language
     * @return \Illuminate\Http\Response
     */
    public function destroy(Language $language)
    {
        try {
            $language->delete();
            request()->session()->flash('success', 'Мову успішно видалено!');
        } catch(\Exception $e) {
            request()->session()->flash('error', 'Мову не видалено!');
        }

        return response($language, 200);
    }

    public function sort(Request $request){
        $language = Language::find($request->id);
        $languageEntity = Language::find($request->positionEntity);

        if ($language && $languageEntity) {
            switch ($request->type) {
                case 'moveAfter':
                    $language->moveAfter($languageEntity);
                    break;
                case 'moveBefore':
                    $language->moveBefore($languageEntity);
                    break;
                default:
                    return response([], 400);
            }
        }

        return response([], 200);
    }
}

resources/views/languages/create.blade.php
@extends('layouts.master')

@section('title') Додавання нової мови @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Додавання нової мови</h4>
                {{ Breadcrumbs::render('languages.create') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('languages.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="title" class="col-sm-2 col-form-label">Назва *</label>
                            <div class="col-sm-5">
                                <input class="form-control" type="text" name="title" value="{{ old('title') }}" id="title">
                                @error('title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="abbreviation" class="col-sm-2 col-form-label">Скорочення *</label>
                            <div class="col-sm-5">
                                <input class="form-control" type="text" name="abbreviation" value="{{ old('abbreviation') }}" id="abbreviation">
                                @error('abbreviation')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="flag" class="col-sm-2 col-form-label">Прапор *</label>
                            <div class="col-sm-5">
                                <input type="file" name="flag" id="flag">
                                @error('flag')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('languages.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

resources/views/languages/edit.blade.php
@extends('layouts.master')

@section('title') Редагування мови@endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Редагування мови</h4>
                {{ Breadcrumbs::render('languages.edit', $language) }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('languages.update', $language) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="title" class="col-sm-2 col-form-label">Назва *</label>
                            <div class="col-sm-5">
                                <input class="form-control" type="text" name="title" value="{{ old('title', $language->title) }}" id="title">
                                @error('title')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="abbreviation" class="col-sm-2 col-form-label">Скорочення *</label>
                            <div class="col-sm-5">
                                <input class="form-control" type="text" name="abbreviation" value="{{ old('abbreviation', $language->abbreviation) }}" id="abbreviation">
                                @error('abbreviation')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="flag" class="col-sm-2 col-form-label">Прапор *</label>
                            <div class="col-sm-5">
                                <div data-id="img-preview">
                                    @if(empty($language->flag) || $errors->has('flag'))
                                        <input type="file" name="flag" id="flag">
                                        @error('flag')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                    @else
                                        <div data-id="img-content">
                                            <input type="hidden" name="flag_path" value="{{ $language->flag }}">
                                            <img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:28px;margin-right: 10px">
                                            <a href="#" class="btn btn-danger btn-sm" data-action="removeImg" data-disabled="flag_path"
                                               data-title="Ви дійсно бажаєте видалити зображення?"><i class="fa fas fa-trash"></i></a>
                                        </div>

                                        <div style="display: none;" data-id="img-upload">
                                            <input type="file" name="flag" id="flag">
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('languages.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

resources/views/languages/index.blade.php
@extends('layouts.master')

@section('title') @lang('translation.languages') @endsection

@section('content')

    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">@lang('translation.languages')</h4>
                {{ Breadcrumbs::render('languages') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">

                    <div class="col-sm-12">
                        <div class="float-right d-md-block mb-3">
                            <a href="{{ route('languages.create') }}"
                               class="btn btn-primary waves-effect waves-light">Додати мову</a>
                        </div>
                    </div>

                    <div class="table-responsive">

                        <table class="table mb-0">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Назва</th>
                                <th>Скорочення</th>
                                <th>Прапор</th>
                                <th>Опції</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody id="sorting" data-entityname="languages">
                            @foreach($languages as $language)
                                <tr class="{{ $language->is_default ? 'blocked' : '' }}" data-itemId="{{ $language->id }}">
                                    <td class="align-middle">{{ $loop->iteration + $languages->firstItem() - 1 }}</td>
                                    <td class="align-middle">{{ $language->title }}</td>
                                    <td class="align-middle">{{ $language->abbreviation }}</td>
                                    <td class="align-middle">@empty(!$language->flag)<img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:24px;">@endempty</td>
                                    <td style="width: 150px;" class="align-middle">
                                        <div class="btn-group">
                                            <a href="{{ route('languages.edit', $language) }}" class="btn btn-primary">
                                                <i class="mdi mdi-pencil"></i>
                                            </a>
                                            <a href="{{ route('languages.destroy', $language) }}" class="btn btn-danger {{ $language->is_default ? 'disabled' : '' }}"
                                               data-message="Ви дійсно хочете видалити мову?" data-action="delete">
                                                <i class="mdi mdi-delete"></i>
                                            </a>
                                        </div>
                                    </td>
                                    <td class="sortable-handle align-middle"><i class="mdi mdi-arrow-up-down" style="cursor: move"></i></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    {{ $languages->links() }}

                </div>
            </div>
        </div>
    </div>
    <!-- End Page-content -->

@endsection

@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script>
        $( function() {
            let changePosition = function(requestData){
                $.ajax({
                    'url': '{{ route('languages.sort') }}',
                    'type': 'POST',
                    'data': requestData,
                    'success': function(data) {
                        //
                    },
                    'error': function(){
                        console.error('Something wrong!');
                    }
                });
            };

            let fixHelper = function(e, ui) {
                ui.children().each(function() {
                    $(this).width($(this).width());
                });
                return ui;
            };

            let $sortableTable = $('#sorting');
            let fixed = '.blocked';
            let newParentContainer;

            function sortingAroundFixedPositions(container) {
                let sortable = $(container);
                let statics = $(fixed, container).detach();
                let tagName = statics.prop('tagName');
                let helper = $('<' + tagName + '/>').prependTo(container);
                statics.each(function() {
                    let target = this.dataset.pos;
                    let targetPosition = $(tagName, sortable).eq(target);
                    if (targetPosition.length === 0) {
                        targetPosition = $(tagName, sortable).eq(target - 1)
                    }
                    $(this).insertAfter(targetPosition);
                });
                helper.remove();
            }

            if ($sortableTable.length > 0) {
                $sortableTable.sortable({
                    handle: '.sortable-handle',
                    axis: 'y',
                    cancel: fixed,
                    cursor: "move",

                    start: function() {
                        $(fixed, $sortableTable).each(function() {
                            this.dataset.pos = $(this).index();
                        });
                    },
                    change: function(e, ui) {
                        sortingAroundFixedPositions(this);
                        if (ui.sender) {
                            newParentContainer = this;
                        }
                        if (newParentContainer) {
                            sortingAroundFixedPositions(newParentContainer);
                        }
                    },

                    update: function(a, b){
                        var $sorted = b.item;

                        var $previous = $sorted.prev();
                        var $next = $sorted.next();

                        if ($previous.length > 0) {
                            changePosition({
                                type: 'moveAfter',
                                id: $sorted.data('itemid'),
                                positionEntity: $previous.data('itemid')
                            });
                        } else if ($next.length > 0) {
                            changePosition({
                                type: 'moveBefore',
                                id: $sorted.data('itemid'),
                                positionEntity: $next.data('itemid')
                            });
                        } else {
                            console.error('Something wrong!');
                        }
                    },
                    helper: fixHelper
                });
            }
        });
    </script>
@endsection