routes/web.php
    return redirect()->route('login');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('index', [\App\Http\Controllers\AdminController::class, 'index'])->name('dashboard');

    Route::middleware('can:languages')->group(function () {
        Route::resource('languages', LanguageController::class)->except(['show']);
        Route::post('languages/sort', [LanguageController::class, 'sort'])->name('languages.sort');
    });

    Route::resource('logs', \App\Http\Controllers\LogController::class)->only(['index'])->middleware('can:logs');

    Route::resource('instructions', \App\Http\Controllers\InstructionController::class)->except('show');
    Route::post('instructions/sort', [\App\Http\Controllers\InstructionController::class, 'sort'])->name('instructions.sort');

    Route::middleware(['can:teachers'])->group(function () {
        Route::resource('teachers', TeacherController::class)->except(['show']);
        Route::post('teachers/get-autocomplete-teacher', [TeacherController::class, 'getAutocompleteTeacher'])
            ->name('teachers.getAutocompleteTeacher');
        Route::post('teachers/get-autocomplete-email', [TeacherController::class, 'getAutocompleteEmail'])
            ->name('teachers.getAutocompleteEmail');
        Route::post('teachers/get-autocomplete-promo-code', [TeacherController::class, 'getAutocompletePromoCode'])
            ->name('teachers.getAutocompletePromoCode');
    });

    Route::middleware(['can:display-students'])->group(function () {
        Route::resource('students', StudentController::class)->except(['show']);
        Route::post('students/get-autocomplete-teacher', [StudentController::class, 'getAutocompleteTeacher'])
            ->name('students.getAutocompleteTeacher');
        Route::post('students/get-autocomplete-student', [StudentController::class, 'getAutocompleteStudent'])
            ->name('students.getAutocompleteStudent');
        Route::post('students/get-autocomplete-group', [StudentController::class, 'getAutocompleteGroup'])
            ->name('students.getAutocompleteGroup');
        Route::post('students/get-autocomplete-email', [StudentController::class, 'getAutocompleteEmail'])
            ->name('students.getAutocompleteEmail');
        Route::post('students/get-autocomplete-promo-code', [StudentController::class, 'getAutocompletePromoCode'])
            ->name('students.getAutocompletePromoCode');
    });

    Route::get('students/export', [StudentController::class, 'export'])->name('students.export')
        ->middleware('can:teachers');
    Route::post('students/action-multiple', [StudentController::class, 'actionMultiple'])
        ->name('students.actionMultiple')
        ->middleware('can:student-actions');

    Route::middleware(['can:groups'])->group(function () {
        Route::resource('groups', GroupController::class)->except(['show']);
        Route::post('groups/get-autocomplete-teacher', [GroupController::class, 'getAutocompleteTeacher'])->name('groups.getAutocompleteTeacher');
        Route::post('groups/get-autocomplete-group', [GroupController::class, 'getAutocompleteGroup'])->name('groups.getAutocompleteGroup');
    });

    Route::resource('category-driver-licenses', CategoryDriverLicenseController::class)
        ->only(['index', 'store'])->middleware('can:category-driver-licenses');

    Route::name('handbook.')->middleware('can:handbook')->prefix('handbook')->group(function () {
        Route::resource('theme-traffic-rules', \App\Http\Controllers\TopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['theme-traffic-rules' => 'topic_traffic_rule']);
    });

    Route::name('theory.')->middleware('can:theory')->prefix('theories')->group(function () {
        Route::resource('internal-theme-traffic-rules', \App\Http\Controllers\InternalTopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['internal-theme-traffic-rules' => 'internal_topic_traffic_rule']);

        Route::resource('item-traffic-rules', \App\Http\Controllers\ItemTrafficRuleController::class)->except(['show']);
        Route::post('item-traffic-rules/get-autocomplete-item', [\App\Http\Controllers\ItemTrafficRuleController::class, 'getAutocompleteItem'])->name('item-traffic-rules.getAutocompleteItem');
        Route::post('item-traffic-rules/sort', [\App\Http\Controllers\ItemTrafficRuleController::class, 'sort'])->name('item-traffic-rules.sort');

        Route::resource('road-markings', TopicRoadMarkingController::class)->except(['show'])->parameters(['road-markings' => 'topic_road_marking']);
        Route::get('road-markings/description', [TopicRoadMarkingController::class, 'editDescription'])->name('road-markings.editDescription');
        Route::post('road-markings/description', [TopicRoadMarkingController::class, 'updateDescription'])->name('road-markings.updateDescription');

        Route::resource('road-signs', TopicRoadSignController::class)->except(['show'])->parameters(['road-signs' => 'topic_road_sign']);
        Route::get('road-signs/description', [TopicRoadSignController::class, 'editDescription'])->name('road-signs.editDescription');
        Route::post('road-signs/description', [TopicRoadSignController::class, 'updateDescription'])->name('road-signs.updateDescription');

        Route::resource('markings', \App\Http\Controllers\MarkingController::class)->except(['show']);
        Route::post('markings/get-autocomplete-markings', [\App\Http\Controllers\MarkingController::class, 'getAutocompleteMarking'])->name('markings.getAutocompleteMarking');
        Route::post('markings/sort', [\App\Http\Controllers\MarkingController::class, 'sort'])->name('markings.sort');

        Route::resource('signs', \App\Http\Controllers\SignController::class)->except(['show']);
        Route::post('signs/get-autocomplete-signs', [\App\Http\Controllers\SignController::class, 'getAutocompleteSign'])->name('signs.getAutocompleteSign');
        Route::post('signs/sort', [\App\Http\Controllers\SignController::class, 'sort'])->name('signs.sort');

        Route::get('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'index'])->name('regulator.index');
        Route::post('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'update'])->name('regulator.update');

        Route::get('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'index'])->name('traffic-light.index');
        Route::post('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'update'])->name('traffic-light.update');

        Route::get('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'index'])->name('video-lessons-traffic-rule.index');
        Route::post('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'update'])->name('video-lessons-traffic-rule.update');
    });

    Route::name('issue-management.')->middleware('can:issue-management')->prefix('issue-management')->group(function () {
        Route::resource('questions', QuestionController::class)->except(['show']);
        Route::get('questions/{question}/duplicate', [QuestionController::class, 'duplicate'])->name('questions.duplicate');
        Route::post('questions/{duplicateQuestion}/store-duplicate', [QuestionController::class, 'storeDuplicate'])->name('questions.store-duplicate');

        Route::resource('questions-complaints', QuestionsComplaintController::class)->only(['index', 'destroy']);

        Route::get('frequent-mistakes', [QuestionController::class, 'frequentMistakes'])->name('frequent-mistakes.index');
        Route::post('frequent-mistakes/reset', [QuestionController::class, 'resetFrequentMistakes'])->name('frequent-mistakes.reset');
    });

    Route::middleware('can:support-services')->group(function () {
        Route::resource('support-services', \App\Http\Controllers\SocialSupportServiceController::class)
            ->except(['show'])
            ->parameters(['support-services' => 'social_support_service']);
    });

    Route::resource('translation-categories', \App\Http\Controllers\TranslationCategoryController::class)
        ->except(['show'])->middleware('can:translations');
    Route::resource('translations', \App\Http\Controllers\TranslationController::class)
        ->except(['show'])->middleware('can:translations');

    Route::resource('subscriptions', SubscriptionController::class)->except(['show']);

    Route::middleware('can:auto-premium')->prefix('auto-premium')->name('auto-premium.')->group(function () {
        Route::get('/', [SubscriptionController::class, 'autoPremium'])->name('index');
        Route::post('/', [SubscriptionController::class, 'updateAutoPremium'])->name('update');
    });

    Route::resource('promo-codes', \App\Http\Controllers\PromoCodeController::class)
        ->except(['show'])->middleware('can:promo-codes');

    Route::middleware('can:updating-msc')->group(function () {
        Route::get('updating-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'index'])->name('updating-msc.index');
        Route::post('updating-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'update'])->name('updating-msc.update');
        Route::get('sync-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'sync'])->name('sync-msc');
        Route::get('diff-sync-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'diffSync'])->name('diff-sync-msc');
    });
    Route::post('promo-codes/get-autocomplete-promo-code', [\App\Http\Controllers\PromoCodeController::class, 'getAutocompletePromoCode'])
        ->name('promo-codes.getAutocompletePromoCode');

    Route::get('report', [\App\Http\Controllers\ReportController::class, 'index'])->name('report.index');
    Route::get('report/import', [\App\Http\Controllers\ReportController::class, 'import'])->name('report.import');

resources/views/handbook/internal-theme-traffic-rules/create.blade.php
@extends('layouts.master')

@section('title') Додавання нової теми @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Додавання нової теми</h4>
                {{ Breadcrumbs::render('internal_theme_traffic_rules.create') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('theory.internal-theme-traffic-rules.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="number" class="col-sm-2 col-form-label">Тема № *</label>
                            <div class="col-sm-2">
                                <input class="form-control @error('number')is-invalid @enderror" type="text"
                                       name="number" value="{{ old('number') }}" id="number">
                                @error('number')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        @foreach($languages as $language)
                            <div class="form-group row">
                                <label for="name_{{ $language->id }}" class="col-sm-2 col-form-label">{{ $language->title }} {{ $language->is_default ? '*' : '' }}</label>
                                <div class="col-sm-7">
                                    <input class="form-control @error('translate.name.' . $language->id)is-invalid @enderror" type="text"
                                           name="translate[name][{{ $language->id }}]"
                                           value="{{ old('translate.name.'. $language->id) }}" id="name_{{ $language->id }}">
                                    @error('translate.name.' . $language->id)<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                </div>
                            </div>
                        @endforeach

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('theory.internal-theme-traffic-rules.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

@section('script')
    <script>
        $(function () {
            document.oninput = function () {
                let input = document.getElementById('number');
                input.value = input.value.replace(/[^\d]/g, '');
            }
        });
    </script>
@endsection

resources/views/handbook/internal-theme-traffic-rules/edit.blade.php
@extends('layouts.master')

@section('title') Редагування теми @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Редагування теми</h4>
                {{ Breadcrumbs::render('internal_theme_traffic_rules.edit', $internalTopicTrafficRule) }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('theory.internal-theme-traffic-rules.update', $internalTopicTrafficRule) }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group row">
                            <label for="number" class="col-sm-2 col-form-label">Тема № *</label>
                            <div class="col-sm-2">
                                <input class="form-control @error('number')is-invalid @enderror" type="text" name="number"
                                       value="{{ old('number', $internalTopicTrafficRule->number) }}" id="number">
                                @error('number')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        @foreach($languages as $language)
                            <div class="form-group row">
                                <label for="name_{{ $language->id }}" class="col-sm-2 col-form-label">{{ $language->title }} {{ $language->is_default ? '*' : '' }}</label>
                                <div class="col-sm-7">
                                    <input class="form-control @error('name_' . $language->id)is-invalid @enderror" type="text"
                                           name="translate[name][{{ $language->id }}]"
                                           value="{{ old('translate.name.'. $language->id, $internalTopicTrafficRule->getTranslate($language->id)->name ?? '') }}"
                                           id="name_{{ $language->id }}">
                                    @error('translate.name.' . $language->id)<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                </div>
                            </div>
                        @endforeach

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ $redirectRoute }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

@section('script')
    <script>
        $(function () {
            document.oninput = function () {
                let input = document.getElementById('number');
                input.value = input.value.replace(/[^\d]/g, '');
            }
        });
    </script>
@endsection

resources/views/handbook/internal-theme-traffic-rules/index.blade.php
@extends('layouts.master')

@section('title') @lang('translation.internal_theme_traffic_rules') @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">@lang('translation.internal_theme_traffic_rules')</h4>
                {{ Breadcrumbs::render('internal_theme_traffic_rules') }}
            </div>
        </div>

    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            @include('layouts.alerts')
            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center mb-3">
                        <div class="col-sm-2">
                            <select id="pagination" class="custom-select">
                                <option value="25" {{ request()->paginate == 25 ? 'selected' : '' }}>25</option>
                                <option value="50" {{ request()->paginate == 50 ? 'selected' : '' }}>50</option>
                                <option value="100" {{ request()->paginate == 100 ? 'selected' : '' }}>100</option>
                            </select>
                        </div>

                        <div class="col-sm-3">
                            <form action="{{ route('theory.internal-theme-traffic-rules.index') }}" method="GET">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="search" value="{{ request()->search ?? '' }}" placeholder="Пошук">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">Пошук</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <div class="col-sm-7">
                            <div class="float-right d-md-block ">
                                <a href="{{ route('theory.internal-theme-traffic-rules.create') }}"
                                   class="btn btn-primary waves-effect waves-light">Додати тему</a>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th style="width: 100px;">Тема №</th>
                                <th>{{ $defaultLanguage->title }}</th>
                                <th>Переклади</th>
                                <th style="width: 110px;">Опції</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($internalTopicTrafficRules as $internalTopicTrafficRule)
                                <tr>
                                    <td>{{ $loop->iteration + $internalTopicTrafficRules->firstItem() - 1 }}</td>
                                    <td>{{ $internalTopicTrafficRule->number }}</td>
                                    <td>{{ $internalTopicTrafficRule->getTranslate($defaultLanguage->id)->name ?? '' }}</td>
                                    <td>
                                        @foreach($languages as $language)
                                            @if(!$language->is_default)
                                                @if(empty($internalTopicTrafficRule->getTranslate($language->id)->name))
                                                    <img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:16px;opacity: 0.2;">
                                                @else
                                                    <img src="{{ \Storage::url($language->flag) }}" style="max-width:64px;max-height:16px;">
                                                @endif
                                            @endif
                                        @endforeach
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{ route('theory.internal-theme-traffic-rules.edit', $internalTopicTrafficRule) }}" class="btn btn-primary">
                                                <i class="mdi mdi-pencil"></i>
                                            </a>
                                            <a href="{{ route('theory.internal-theme-traffic-rules.destroy', $internalTopicTrafficRule) }}" class="btn btn-danger"
                                               data-message="Ви дійсно хочете видалити тему?" data-action="delete">
                                                <i class="mdi mdi-delete"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    {{ $internalTopicTrafficRules->appends(request()->except('page'))->links() }}
                </div>
            </div>
        </div>
    </div>
    <!-- End Page-content -->

@endsection

@section('script-bottom')
    <script>
        $(".select2").select2({
            minimumResultsForSearch: Infinity
        });
    </script>
@endsection