routes/web.php
        Route::post('students/get-autocomplete-email', [StudentController::class, 'getAutocompleteEmail'])
            ->name('students.getAutocompleteEmail');
        Route::post('students/get-autocomplete-promo-code', [StudentController::class, 'getAutocompletePromoCode'])
            ->name('students.getAutocompletePromoCode');
    });

    Route::get('students/export', [StudentController::class, 'export'])->name('students.export')
        ->middleware('can:teachers');
    Route::post('students/action-multiple', [StudentController::class, 'actionMultiple'])
        ->name('students.actionMultiple')
        ->middleware('can:student-actions');

    Route::middleware(['can:groups'])->group(function () {
        Route::resource('groups', GroupController::class)->except(['show']);
        Route::post('groups/get-autocomplete-teacher', [GroupController::class, 'getAutocompleteTeacher'])->name('groups.getAutocompleteTeacher');
        Route::post('groups/get-autocomplete-group', [GroupController::class, 'getAutocompleteGroup'])->name('groups.getAutocompleteGroup');
    });

    Route::resource('category-driver-licenses', CategoryDriverLicenseController::class)
        ->only(['index', 'store'])->middleware('can:category-driver-licenses');

    Route::name('handbook.')->middleware('can:handbook')->prefix('handbook')->group(function () {
        Route::resource('theme-traffic-rules', \App\Http\Controllers\TopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['theme-traffic-rules' => 'topic_traffic_rule']);
    });

    Route::name('theory.')->middleware('can:theory')->prefix('theories')->group(function () {
        Route::resource('internal-theme-traffic-rules', \App\Http\Controllers\InternalTopicTrafficRuleController::class)
            ->except(['show'])
            ->parameters(['internal-theme-traffic-rules' => 'internal_topic_traffic_rule']);

        Route::resource('item-traffic-rules', \App\Http\Controllers\ItemTrafficRuleController::class)->except(['show']);
        Route::post('item-traffic-rules/get-autocomplete-item', [\App\Http\Controllers\ItemTrafficRuleController::class, 'getAutocompleteItem'])->name('item-traffic-rules.getAutocompleteItem');
        Route::post('item-traffic-rules/sort', [\App\Http\Controllers\ItemTrafficRuleController::class, 'sort'])->name('item-traffic-rules.sort');

        Route::resource('road-markings', TopicRoadMarkingController::class)->except(['show'])->parameters(['road-markings' => 'topic_road_marking']);
        Route::get('road-markings/description', [TopicRoadMarkingController::class, 'editDescription'])->name('road-markings.editDescription');
        Route::post('road-markings/description', [TopicRoadMarkingController::class, 'updateDescription'])->name('road-markings.updateDescription');

        Route::resource('road-signs', TopicRoadSignController::class)->except(['show'])->parameters(['road-signs' => 'topic_road_sign']);
        Route::get('road-signs/description', [TopicRoadSignController::class, 'editDescription'])->name('road-signs.editDescription');
        Route::post('road-signs/description', [TopicRoadSignController::class, 'updateDescription'])->name('road-signs.updateDescription');

        Route::resource('markings', \App\Http\Controllers\MarkingController::class)->except(['show']);
        Route::post('markings/get-autocomplete-markings', [\App\Http\Controllers\MarkingController::class, 'getAutocompleteMarking'])->name('markings.getAutocompleteMarking');
        Route::post('markings/sort', [\App\Http\Controllers\MarkingController::class, 'sort'])->name('markings.sort');

        Route::resource('signs', \App\Http\Controllers\SignController::class)->except(['show']);
        Route::post('signs/get-autocomplete-signs', [\App\Http\Controllers\SignController::class, 'getAutocompleteSign'])->name('signs.getAutocompleteSign');
        Route::post('signs/sort', [\App\Http\Controllers\SignController::class, 'sort'])->name('signs.sort');

        Route::get('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'index'])->name('regulator.index');
        Route::post('regulator', [\App\Http\Controllers\TranslateRegulatorController::class, 'update'])->name('regulator.update');

        Route::get('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'index'])->name('traffic-light.index');
        Route::post('traffic-light', [\App\Http\Controllers\TranslateTrafficLightController::class, 'update'])->name('traffic-light.update');

        Route::get('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'index'])->name('video-lessons-traffic-rule.index');
        Route::post('video-lessons-traffic-rule', [\App\Http\Controllers\TranslateVideoLessonsTrafficRuleController::class, 'update'])->name('video-lessons-traffic-rule.update');
    });

    Route::name('issue-management.')->middleware('can:issue-management')->prefix('issue-management')->group(function () {
        Route::resource('questions', QuestionController::class)->except(['show']);
        Route::get('questions/{question}/duplicate', [QuestionController::class, 'duplicate'])->name('questions.duplicate');
        Route::post('questions/{duplicateQuestion}/store-duplicate', [QuestionController::class, 'storeDuplicate'])->name('questions.store-duplicate');

        Route::resource('questions-complaints', QuestionsComplaintController::class)->only(['index', 'destroy']);

        Route::get('frequent-mistakes', [QuestionController::class, 'frequentMistakes'])->name('frequent-mistakes.index');
        Route::post('frequent-mistakes/reset', [QuestionController::class, 'resetFrequentMistakes'])->name('frequent-mistakes.reset');
    });

    Route::middleware('can:support-services')->group(function () {
        Route::resource('support-services', \App\Http\Controllers\SocialSupportServiceController::class)
            ->except(['show'])
            ->parameters(['support-services' => 'social_support_service']);
    });

    Route::resource('translation-categories', \App\Http\Controllers\TranslationCategoryController::class)
        ->except(['show'])->middleware('can:translations');
    Route::resource('translations', \App\Http\Controllers\TranslationController::class)
        ->except(['show'])->middleware('can:translations');

    Route::resource('subscriptions', SubscriptionController::class)->except(['show']);

    Route::middleware('can:auto-premium')->prefix('auto-premium')->name('auto-premium.')->group(function () {
        Route::get('/', [SubscriptionController::class, 'autoPremium'])->name('index');
        Route::post('/', [SubscriptionController::class, 'updateAutoPremium'])->name('update');
    });

    Route::resource('promo-codes', \App\Http\Controllers\PromoCodeController::class)
        ->except(['show'])->middleware('can:promo-codes');

    Route::middleware('can:updating-msc')->group(function () {
        Route::get('updating-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'index'])->name('updating-msc.index');
        Route::post('updating-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'update'])->name('updating-msc.update');
        Route::get('sync-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'sync'])->name('sync-msc');
        Route::get('diff-sync-msc', [\App\Http\Controllers\UpdatingMSCController::class, 'diffSync'])->name('diff-sync-msc');
    });
    Route::post('promo-codes/get-autocomplete-promo-code', [\App\Http\Controllers\PromoCodeController::class, 'getAutocompletePromoCode'])
        ->name('promo-codes.getAutocompletePromoCode');

    Route::get('report', [\App\Http\Controllers\ReportController::class, 'index'])->name('report.index');
    Route::get('report/import', [\App\Http\Controllers\ReportController::class, 'import'])->name('report.import');

    Route::middleware('can:payments')->group(function () {
        Route::resource('payments', PaymentController::class)->only(['index']);
        Route::post('payments/get-autocomplete-student', [PaymentController::class, 'getAutocompleteStudent'])
            ->name('payments.getAutocompleteStudent');
    });

    Route::resource('text-pages', \App\Http\Controllers\TextPageController::class)->except(['show'])
        ->middleware('can:text-pages');

    Route::resource('push-notifications', \App\Http\Controllers\PushNotificationController::class)
        ->only(['index', 'store'])
        ->middleware('can:push-notifications');

    Route::middleware('can:general-settings')->group(function () {
        Route::name('general-settings.')->prefix('general-settings')->group(function () {
            Route::get('/', [\App\Http\Controllers\GeneralSettingController::class, 'index'])->name('index');
            Route::post('/', [\App\Http\Controllers\GeneralSettingController::class, 'store'])->name('store');
        });

        Route::get('sync-api-questions', function () {
            Artisan::call('api-question:sync');
            request()->session()->flash('success', nl2br(Artisan::output()));

            return redirect()->back();
        })->name('sync-api-questions');

        Route::get('sync-api-theory', function () {
            Artisan::call('api-theory:sync');
            request()->session()->flash('success', nl2br(Artisan::output()));

            return redirect()->back();
        })->name('sync-api-theory');
    });

    Route::name('imageUpload.')->prefix('image-upload')->group(function () {
        Route::post('/tinymce', [\App\Http\Controllers\ImageUploadController::class, 'tinymce'])->name('tinymce');
        Route::post('/markdown-editor', [\App\Http\Controllers\ImageUploadController::class, 'markdownEditor'])->name('markdownEditor');
        Route::post('/remove-markdown-editor', [\App\Http\Controllers\ImageUploadController::class, 'removeMarkdownEditor'])->name('removeMarkdownEditor');

app/Models/SocialSupportService.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class SocialSupportService extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'link', 'logo'];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function($socialSupportService) {
            Storage::delete($socialSupportService->logo);
        });
    }
}

app/Http/Controllers/API/v1/SocialSupportServiceController.php
<?php

namespace App\Http\Controllers\API\v1;

use App\Http\Controllers\Controller;
use App\Http\Resources\SocialSupportServiceResource;
use App\Models\SocialSupportService;

class SocialSupportServiceController extends Controller
{
    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        return $this->apiResponse(SocialSupportServiceResource::collection(SocialSupportService::all()));
    }
}

app/Http/Controllers/SocialSupportServiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SocialSupportServices\StoreRequest;
use App\Http\Requests\SocialSupportServices\UpdateRequest;
use App\Models\SocialSupportService;
use Illuminate\Support\Facades\Storage;

class SocialSupportServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return mixed
     */
    public function index()
    {
        $socialSupportServices = SocialSupportService::all();

        return view('social-support-services.index', compact('socialSupportServices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return mixed
     */
    public function create()
    {
        return view('social-support-services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\SocialSupportServices\StoreRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreRequest $request)
    {
        $socialSupportService = SocialSupportService::create($request->validated());

        if ($request->hasFile('logo')) {
            $socialSupportService->logo = $request->logo->storePublicly('public/support-services/logo');
            $socialSupportService->save();
        }

        return $request->action == 'save_and_stay' ?
            redirect()->route('support-services.edit', $socialSupportService)->with('success', 'Службу підтримки успішно створено!') :
            redirect()->route('support-services.index')->with('success', 'Службу підтримки успішно створено!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SocialSupportService  $socialSupportService
     * @return mixed
     */
    public function edit(SocialSupportService $socialSupportService)
    {
        return view('social-support-services.edit', compact('socialSupportService'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\SocialSupportServices\UpdateRequest  $request
     * @param  \App\Models\SocialSupportService  $socialSupportService
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, SocialSupportService $socialSupportService)
    {
        $socialSupportService->update($request->validated());

        if ($request->hasFile('logo')) {
            Storage::delete($socialSupportService->logo);

            $socialSupportService->logo = $request->logo->storePublicly('public/support-services/logo');
            $socialSupportService->save();
        }

        return $request->action == 'save_and_stay' ?
            redirect()->route('support-services.edit', $socialSupportService)->with('success', 'Службу підтримки успішно оновлено!') :
            redirect()->route('support-services.index')->with('success', 'Службу підтримки успішно оновлено!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SocialSupportService  $socialSupportService
     * @return \Illuminate\Http\Response
     */
    public function destroy(SocialSupportService $socialSupportService)
    {
        try {
            $socialSupportService->delete();
            request()->session()->flash('success', 'Служба підтримки успішно видалено!');
        } catch(\Exception $e) {
            request()->session()->flash('error', 'Помилка. Служба підтримки не видалено!');
        }

        return response($socialSupportService, 200);
    }
}

resources/views/social-support-services/create.blade.php
@extends('layouts.master')

@section('title') Додавання нової служби підтримки @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Додавання нової служби підтримки</h4>
                {{ Breadcrumbs::render('social-support-service.create') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('support-services.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">Назва *</label>
                            <div class="col-sm-5">
                                <input class="form-control @error('name')is-invalid @enderror" type="text" name="name" value="{{ old('name') }}" id="name">
                                @error('name')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="link" class="col-sm-2 col-form-label">Посилання *</label>
                            <div class="col-sm-5">
                                <input class="form-control @error('link')is-invalid @enderror" type="text" name="link" value="{{ old('link') }}" id="link">
                                @error('link')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="logo" class="col-sm-2 col-form-label">Логотип *</label>
                            <div class="col-sm-5">
                                <input type="file" name="logo" id="logo">
                                <div><span style="font-size: 11px;">Розмір: до 10кб; формат: jpeg,jpg,png,gif; роздільна здатність: 50x50px</span></div>
                                @error('logo')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('support-services.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

resources/views/social-support-services/edit.blade.php
@extends('layouts.master')

@section('title') Редагування служби підтримки @endsection

@section('content')
    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">Редагування служби підтримки</h4>
                {{ Breadcrumbs::render('social-support-service.edit', $socialSupportService) }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{ route('support-services.update', $socialSupportService) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">Назва *</label>
                            <div class="col-sm-5">
                                <input class="form-control @error('name')is-invalid @enderror" type="text" name="name"
                                       value="{{ old('name', $socialSupportService->name) }}" id="name">
                                @error('name')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="link" class="col-sm-2 col-form-label">Посилання *</label>
                            <div class="col-sm-5">
                                <input class="form-control @error('link')is-invalid @enderror" type="text" name="link"
                                       value="{{ old('link', $socialSupportService->link) }}" id="link">
                                @error('link')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="logo" class="col-sm-2 col-form-label">Логотип *</label>
                            <div class="col-sm-5">

                                <div data-id="img-preview">
                                    @if(empty($socialSupportService->logo) || $errors->has('logo'))
                                        <input type="file" name="logo" id="logo">
                                        <div><span style="font-size: 11px;">Розмір: до 10кб; формат: jpeg,jpg,png,gif; роздільна здатність: 50x50px</span></div>
                                        @error('logo')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror
                                    @else
                                        <div data-id="img-content">
                                            <input type="hidden" name="logo_path" value="{{ $socialSupportService->logo }}">
                                            <img src="{{ \Storage::url($socialSupportService->logo) }}" style="max-width:50px;max-height:50px;margin-right: 10px;">
                                            <a href="#" class="btn btn-danger btn-sm" data-action="removeImg" data-disabled="logo_path"
                                               data-title="Ви дійсно бажаєте видалити зображення?"><i class="fa fas fa-trash"></i></a>
                                        </div>

                                        <div style="display: none;" data-id="img-upload">
                                            <input type="file" name="logo" id="logo">
                                            <div><span style="font-size: 11px;">Розмір: до 10кб; формат: jpeg,jpg,png,gif; роздільна здатність: 50x50px</span></div>
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" name="action" value="save"
                                        class="btn btn-primary waves-effect waves-light">Зберегти</button>
                                <button type="submit" name="action" value="save_and_stay"
                                        class="btn btn-primary waves-effect waves-light">Зберегти і залишитися</button>
                                <a href="{{ route('support-services.index') }}"
                                   class="btn btn-secondary waves-effect waves-light">Скасувати</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->
@endsection

resources/views/social-support-services/index.blade.php
@extends('layouts.master')

@section('title') @lang('translation.support_service') @endsection

@section('content')

    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="page-title-box">
                <h4 class="font-size-18">@lang('translation.support_service')</h4>
                {{ Breadcrumbs::render('social-support-service') }}
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-lg-12">
            @include('layouts.alerts')

            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center mb-3">
                        <div class="col-sm-12">
                            <div class="float-right d-md-block ">
                                <a href="{{ route('support-services.create') }}"
                                   class="btn btn-primary waves-effect waves-light">Додати службу підтримки</a>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Назва</th>
                                <th>Посилання</th>
                                <th>Логотип</th>
                                <th>Опції</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($socialSupportServices as $socialSupportService)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $socialSupportService->name }}</td>
                                    <td>{{ $socialSupportService->link }}</td>
                                    <td>@empty(!$socialSupportService->logo)<img src="{{ \Storage::url($socialSupportService->logo) }}" style="max-width:50px;max-height:50px;">@endempty</td>
                                    <td style="width: 150px;">
                                        <div class="btn-group">
                                            <a href="{{ route('support-services.edit', $socialSupportService) }}" class="btn btn-primary">
                                                <i class="mdi mdi-pencil"></i>
                                            </a>
                                            <a href="{{ route('support-services.destroy', $socialSupportService) }}" class="btn btn-danger"
                                               data-message="Видалити?" data-action="delete">
                                                <i class="mdi mdi-delete"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page-content -->
@endsection